name: Autograding Tests
"on":
  pull_request:
    branches: [main]

permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    env:
      # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
      # in GitHub repo → Settings → Secrets → Actions
      E2E: true
      CI: true
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COURSE_ID: full-stack-development-comp3036-2026
      PASSWORD: 123
      JWT_SECRET: secret
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: http://127.0.0.1:3001/
      # VERCEL_URL: http://127.0.0.1:3001/
      #TURBO_TOKEN: ${{secrets.TURBO_TOKEN}}
      #TURBO_TEAM: team_FXFYQlL6HSM7CAamFdBZ5A6x
      SKIP_ENV_VALIDATION: true
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PNPM 📦
        uses: pnpm/action-setup@v4
        with:
          version: 10.2.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies 🧪
        run: pnpm install
      - name: Install Playwright Browsers
        working-directory: tests/playwright
        run: pnpm playwright install chromium --with-deps
      - name: Push Database 📦
        run: pnpm --filter @repo/db db:push
      - name: Build the project 🏗
        run: pnpm turbo build
      - name: Playwright - Run setup once
        working-directory: tests/playwright
        run: pnpm playwright test --project=setup

      ####################
      # STOREFRONT TESTS
      ####################
      - name: Test Storefront with Playwright
        id: npm1
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with:
          working-directory: .
          test-name: Part 1 - Client
          command: pnpm turbo test-1
          timeout: 10
          max-score: 1
      ####################
      # ADMIN TESTS
      ####################
      - name: Test Admin with Playwright
        id: npm2
        uses: WesternSydneyUniversity/autograding-command-grader@v2
        continue-on-error: true
        with:
          working-directory: .
          test-name: Part 1 - Client
          command: pnpm turbo test-2
          timeout: 10
          max-score: 1
      ####################
      # REPORTING TO SKILLPIES
      ####################
      - name: Report Result to SkillPies
        if: always() # run on failed tests as well
        continue-on-error: true
        uses: tomitrescak/skillpies-reporting@v1.0
        with:
          courseId: ${{env.COURSE_ID}}
          sectionId: major-assignment-in-ci-cd-and-devops
          testResult: ${{steps.npm1.outputs.result}} #pass when both tests pass, fail otherwise

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          NPM1_RESULTS: "${{steps.npm1.outputs.result}}"
          NPM2_RESULTS: "${{steps.npm2.outputs.result}}"
        with:
          runners: npm1, npm2
